server:
  port: 8081
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 512

spring:
  application:
    name: core-cuentas-service

logging:
  level:
    root: INFO
    cl.duoc.bancoxyz.bff: INFO
