server:
  port: 8081
  compression:
    enabled: true
    mime-types: application/json

spring:
  application:
    name: core-cuentas-service

logging:
  level:
    root: INFO
    cl.duoc.bancoxyz.bff: INFO
